---
  #extends:
  #  - eslint:recommended
  #  - 'plugin:@typescript-eslint/recommended'
  #- prettier
  #- plugin:prettier/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
rules:
  curly:
    - error
    - "all"
  #prettier/prettier:
  #  - error
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
